MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- name: ModbusTest
  id: 2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27
  class: org.apache.nifi.minifi.processors.GetModbusTCP
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1000 ms
  auto-terminated relationships list:
    - failure
  Properties:
    Host: 10.90.18.93
    Port: 502
- name: PutMemoryMap
  id: 8a534b4a-2b4a-4e1e-ab07-8a09fa08f848
  class: org.apache.nifi.minifi.extensions.cache.PutMemoryMap
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list:
  - success
  - failure
  Properties:
    Memory Map Service: fd0bb6e7-5bd7-3966-0000-000000000000
    Cache Expire: 'true'
    Cache Expire Attrs: deviceCode
Controller Services:
- id: fd0bb6e7-5bd7-3966-0000-000000000000
  name: MemoryMapControllerService
  type: org.apache.nifi.minifi.extensions.cache.MemoryMapControllerService
  Properties:
    Bucket Num: '31'
Connections:
- name: ModbusTest/success/PutMemoryMap
  source id: 2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27
  source relationship name: success
  destination id: 8a534b4a-2b4a-4e1e-ab07-8a09fa08f848
Remote Process Groups: []
