MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- name: ListenHttpTest
  id: 2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27
  class: org.apache.nifi.minifi.processors.ListenHTTP
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1000 ms
  auto-terminated relationships list:
    - success
  Properties:
    Base Path: test
    Listening Port: 8777
Controller Services: []
Remote Process Groups: []
